export default games = [
    {   
        id: 1,
        ready: true,
        name: 'Тапқыр',
        modalName: 'TestPlay',
        rule : 'Дұрыс аударманы таңда',
        description1 : 'Латынша әріптерді жылдам оқып үйретеді',
        description2 : 'Әріпті жылдам ажыратып үйретеді',
        iconName: 'polymer',
        color: '#F64A81',
        longRule: "Берілген сөздің дұрыс аудармасын таңда",
        storageKey: 'testPlayKey',
        backgroundColor: '#005166',
    },
    {
        id: 2,
        name: 'Байқағыш',
        modalName: 'ObserverPlay',
        ready: true,
        rule : 'Қате сөзді тап',
        description1 : 'Сөйлемді латынша оқу қабілетін дамытады',
        description2 : 'Жылдам ойлау қабілетін дамытады ',
        iconName: 'grain',
        color: '#FC6644',
        longRule: "Берілген сөйлемнің аудармасынан қате сөзді тап",
        storageKey: 'observerPlayKey',
        backgroundColor: '#004F75',
    },
    {
        id: 3,
        name: 'Әріпгер',
        modalName: 'LetterPlay',
        ready: true,
        rule : 'Қате әріпті тап',
        description1 : 'Әріпттерді тез ажыратуға үйретеді',
        description2 : 'Қате қойылған әріпті тез аңғаруға үйретеді',
        iconName: 'pets',
        color: '#7970FF',
        longRule: "Берілген сөздің аудармасынан қате әріпті тап",
        storageKey: 'letterPlayKey',
        backgroundColor: 'rgb(251, 188, 197)',
    },
    {
        id: 4,
        name: 'Құрастыр',
        modalName: 'ConstructPlay',
        ready: true,
        rule : 'Сөзді құрау',
        description1 : 'Латын әріпттерінен сөз құрап үйреттеді',
        description2 : 'Жылдам ойлау қабілетін арттырады',
        iconName: 'edit',
        color: '#FFB13D',
        longRule: "Берілген әріптерді қолдана отырып сөзді аудар",
        storageKey: 'constructPlayKey',
        backgroundColor: '#FDAC4E',
    },
]